// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RCCWebApi.Models
{
    public partial class TritSmsRecipient
    {
        public int SmsRecipientId { get; set; }
        public string SmsMessageId { get; set; }
        public string SmsStatusId { get; set; }
        public int UserId { get; set; }
        public DateTime SaleDate { get; set; }
        public string BillNumber { get; set; }
        public int CreatedBy { get; set; }
        public DateTime CreatedDate { get; set; }
        public int? SpId { get; set; }
    }
}