// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RCCWebApi.Models
{
    public partial class TritUserRole
    {
        public int UserRoleId { get; set; }
        public int UserId { get; set; }
        public int RoleId { get; set; }
        public int CreatedBy { get; set; }
        public DateTime CreatedDt { get; set; }

        public virtual TritUser CreatedByNavigation { get; set; }
        public virtual TritRole Role { get; set; }
        public virtual TritUser User { get; set; }
    }
}