// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RCCWebApi.Models
{
    public partial class TritRole
    {
        public TritRole()
        {
            TritUserRoles = new HashSet<TritUserRole>();
        }

        public int RoleId { get; set; }
        public string RoleDesc { get; set; }

        public virtual ICollection<TritUserRole> TritUserRoles { get; set; }
    }
}