// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RCCWebApi.Models
{
    public partial class TritUserCustomerVendor
    {
        public TritUserCustomerVendor()
        {
            TritUsers = new HashSet<TritUser>();
        }

        public string UserCustomerVendorCode { get; set; }
        public string Description { get; set; }

        public virtual ICollection<TritUser> TritUsers { get; set; }
    }
}