// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace RCCWebApi.Models
{
    public partial class usp_RIT_getCustomersOrdersByDateMobileResult
    {
        public int USER_ID { get; set; }
        public string USER_NAME { get; set; }
        public int ORDER_CAGES { get; set; }
    }
}
